# Generated by Django 5.2.7 on 2026-04-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event type name (e.g., Corporate Event)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this event type')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-briefcase)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this event type in forms')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('event_venue', models.CharField(blank=True, max_length=255, verbose_name='Event Venue')),
                ('estimated_guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Guests')),
                ('budget_range', models.CharField(blank=True, choices=[('under_500', 'Under $500'), ('500_2000', '$500 - $2,000'), ('2000_5000', '$2,000 - $5,000'), ('5000_10000', '$5,000 - $10,000'), ('over_10000', 'Over $10,000'), ('not_specified', 'Not specified')], default='not_specified', max_length=50, verbose_name='Budget Range')),
                ('services_required', models.JSONField(blank=True, default=list, help_text='List of services required (Audio, Visual, Lighting, etc.)', verbose_name='Services Required')),
                ('message', models.TextField(verbose_name='Message / Requirements')),
                ('how_did_you_hear', models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('event', 'Saw at an event'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='other', max_length=100, verbose_name='How did you hear about us?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20, verbose_name='Quote Status')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Assigned To')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='Home.eventtype', verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Home.quote')),
            ],
            options={
                'verbose_name': 'Quote Comment',
                'verbose_name_plural': 'Quote Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='Home_quote_status_fb2172_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['event_type'], name='Home_quote_event_t_c765f8_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at'], name='Home_quote_created_841f1a_idx'),
        ),
    ]
