# Generated by Django 5.2.7 on 2026-04-02 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recent_work/', verbose_name='Project Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_works', to='Home.eventtype', verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Recent Work',
                'verbose_name_plural': 'Recent Works',
                'ordering': ['-created_at'],
            },
        ),
    ]
