# Generated by Django 5.2.7 on 2026-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_recentwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Audio)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this service')),
                ('is_active', models.BooleanField(default=True, help_text='Show this service in forms')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in form checkboxes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
